#!/bin/sh -e
# postinst script for steam
#
# see: dh_installdeb(1)

# popup update notification for the user to run Steam and complete the per-user install
PACKAGE=steam
UPDATENOTIFIERDIR=/var/lib/update-notifier/user.d
if [ -d $UPDATENOTIFIERDIR ] ; then
    cat >$UPDATENOTIFIERDIR/$PACKAGE-install-notify <<__EOF__
Name: Steam Installer
Priority: Medium
Command: /usr/bin/$PACKAGE
DontShowAfterReboot: False
ButtonText: Start Steam
DisplayIf: test ! -x ~/.steam/$PACKAGE/ubuntu12_32/steam
OnlyAdminUsers: False
Description: 
 Start Steam to complete installation of the Steam for the current user.
__EOF__
fi


